- title: Art space
  description:
  fa-icon: fa-object-group
  link: /art/

- title: Cultural events
  description:
  fa-icon: fa-handshake-o
  link: /events/

- title: Rustic homestay
  description:
  fa-icon: fa-tree
  link: /spaces/

- title: Art residencies
  description:
  fa-icon: fa-paint-brush
  link:
