- title: Contemporary art space
  description:
  fa-icon: fa-object-group
  link:

- title: Rustic homestay
  description:
  fa-icon: fa-tree
  link:

- title: Art residencies
  description:
  fa-icon: fa-paint-brush
  link:
