- title: Art space
  description:
  fa-icon: fa-object-group
  link:

- title: Cultural events
  description:
  fa-icon: fa-handshake-o
  link:

- title: Rustic homestay
  description:
  fa-icon: fa-tree
  link:

- title: Art residencies
  description:
  fa-icon: fa-paint-brush
  link:
